-- Generated by scripts/assemble-migration.js from supabase/sql/.
-- Included in the generated migration by scripts/assemble-migration.js.
create or replace function sms_private.api_action(u text,t text,action text,p jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare c public.sms_contacts; g public.sms_automation_groups; eid uuid; r jsonb; n int; v bigint; begin
 perform sms_private.require_admin(u);
 if (select count(*) from sms_private.audit where actor=u and created_at>now()-interval '1 minute')>=120 then raise exception 'Too many actions; retry shortly'; end if;
 insert into sms_private.audit(tenant_id,actor,action,detail) values(case when action='create_business' then null else t end,u,action,jsonb_build_object('record_id',p->>'id'));
 if action='create_business' then
   if not exists(select from pg_timezone_names where name=p->>'timeZone') then raise exception 'Invalid timezone'; end if;
   insert into public.sms_businesses(tenant_id,name,time_zone) values(p->>'id',p->>'name',p->>'timeZone');
   insert into sms_private.providers(tenant_id) values(p->>'id');
   insert into public.sms_business_memberships(tenant_id,clerk_user_id) values(p->>'id',u);
   return jsonb_build_object('id',p->>'id','name',p->>'name','timeZone',p->>'timeZone','status','pending');
 end if;
 if not exists(select from public.sms_businesses where tenant_id=t) then raise exception 'Unknown business'; end if;
 if action='contact' then
   insert into public.sms_contacts(tenant_id,phone,name,email,source,metadata)
   values(t,p->>'phone',coalesce(p->>'name',''),p->>'email',coalesce(p->>'source','contact'),coalesce(p->'metadata','{}'))
   on conflict(tenant_id,phone) do update set name=excluded.name,email=excluded.email,source=excluded.source,metadata=excluded.metadata,updated_at=now() returning * into c;
   return to_jsonb(c);
 elsif action='consent' then
   if coalesce(length(p->>'evidence'),0)=0 then raise exception 'Consent evidence required'; end if;
   select * into strict c from public.sms_contacts where tenant_id=t and phone=p->>'phone' for update;
   update public.sms_contacts set opted_out=not (p->>'consent')::boolean,marketing_consent=(p->>'consent')::boolean,generation=generation+1,updated_at=now() where tenant_id=t and id=c.id;
   insert into public.sms_consent_events(tenant_id,contact_id,consent,source,evidence) values(t,c.id,(p->>'consent')::boolean,'admin',p->>'evidence');
   if not (p->>'consent')::boolean then perform sms_private.cancel_contact(t,c.id); end if;
   return jsonb_build_object('ok',true);
 elsif action='send' then
   return sms_private.outbox(t,p->>'idempotencyKey',p-'idempotencyKey');
 elsif action='group' then
   if jsonb_array_length(p->'rule'->'steps') not between 1 and 30 then raise exception '1-30 steps required'; end if;
   insert into public.sms_automation_groups(tenant_id,id,name,description,kind,rule,active)
   values(t,p->>'id',p->>'name',coalesce(p->>'description',''),coalesce(p->>'kind','custom'),p->'rule',coalesce((p->>'active')::boolean,true))
   on conflict(tenant_id,id) do update set name=excluded.name,description=excluded.description,rule=excluded.rule,active=excluded.active,version=sms_automation_groups.version+1,updated_at=now() returning * into g;
   delete from public.sms_automation_steps where tenant_id=t and group_id=g.id;
   n:=0;
   for r in select value from jsonb_array_elements(p->'rule'->'steps') loop
     insert into public.sms_automation_steps values(t,g.id,n,r->>'template',(r->>'delayCount')::integer,r->>'delayUnit'); n:=n+1;
   end loop;
   update public.sms_automation_enrollments set generation=generation+1,next_run_at=now() where tenant_id=t and category_id=g.id and status='active';
   return to_jsonb(g);
 elsif action='delete_group' then
   update public.sms_automation_groups set active=false,version=version+1 where tenant_id=t and id=p->>'id';
   update public.sms_automation_enrollments set status='cancelled',generation=generation+1 where tenant_id=t and category_id=p->>'id' and status in ('active','paused');
   return jsonb_build_object('ok',true);
 elsif action='ai_settings' then
   insert into public.sms_ai_settings(tenant_id,group_id,enabled,instructions) values(t,p->>'id',coalesce((p->>'enabled')::boolean,false),coalesce(p->>'instructions',''))
   on conflict(tenant_id,group_id) do update set enabled=excluded.enabled,instructions=excluded.instructions,updated_at=now();
   update public.sms_thread_contacts set generation=generation+1 where tenant_id=t;
   return jsonb_build_object('ok',true);
 elsif action='enroll' then
   select * into strict c from public.sms_contacts where tenant_id=t and phone=p->>'phone' for update;
   select * into strict g from public.sms_automation_groups where tenant_id=t and id=p->>'categoryId' and active;
   if c.opted_out or (g.kind<>'reminder' and not c.marketing_consent) then raise exception 'Consent required' using errcode='42501'; end if;
   if g.kind='reminder' and ((p->>'appointment_at') is null or (p->>'appointment_at')::timestamptz<=now()) then raise exception 'Future appointment required'; end if;
   update public.sms_automation_enrollments set status='cancelled',generation=generation+1 where tenant_id=t and contact_id=c.id and category_id=g.id and status in ('active','paused');
   insert into public.sms_automation_enrollments(tenant_id,contact_id,category_id,next_run_at,appointment_at,metadata)
   values(t,c.id,g.id,now(),(p->>'appointment_at')::timestamptz,coalesce(p->'metadata','{}')) returning id into eid;
   return jsonb_build_object('id',eid,'status','active');
 elsif action='unenroll' then
   update public.sms_automation_enrollments set status='cancelled',generation=generation+1 where tenant_id=t
     and contact_id=(select id from public.sms_contacts where tenant_id=t and phone=p->>'phone') and category_id=p->>'categoryId' and status in ('active','paused');
   return jsonb_build_object('ok',true);
 elsif action in ('read','pause','resume') then
   update public.sms_thread_contacts set unread_count=case when action='read' then 0 else unread_count end,
     ai_paused=case when action='pause' then true when action='resume' then false else ai_paused end,
     generation=generation+case when action='read' then 0 else 1 end where tenant_id=t and phone=p->>'phone';
   return jsonb_build_object('ok',true);
 elsif action='retry_job' then
   select to_jsonb(j) into strict r from sms_private.jobs j where tenant_id=t and id=(p->>'id')::uuid and status='failed' for update;
   update sms_private.jobs set status='queued',attempts=0,available_at=now(),lease_token=null,leased_until=null,
     queue_msg_id=(select pgmq.send(r->>'queue',jsonb_build_object('job_id',r->>'id'),0)) where id=(r->>'id')::uuid;
   return jsonb_build_object('ok',true);
 elsif action='provision' then
   return jsonb_build_object('jobId',sms_private.enqueue(t,'provisioning_jobs','provision',jsonb_build_object('name',p->>'name')),'status','queued');
 end if;
 raise exception 'Unknown operation';
end $$;

create or replace function sms_private.cancel_contact(t text,cid uuid) returns void language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare ph text; begin
 select phone into strict ph from public.sms_contacts where tenant_id=t and id=cid;
 update public.sms_automation_enrollments set status='cancelled',generation=generation+1 where tenant_id=t and contact_id=cid and status in ('active','paused');
 update public.sms_thread_contacts set generation=generation+1 where tenant_id=t and phone=ph;
 update sms_private.jobs set status='cancelled',updated_at=now() where tenant_id=t and status in ('queued','retry','processing')
   and (payload->'request'->>'phone'=ph or payload->>'phone'=ph);
 update public.sms_messages set status='cancelled',updated_at=now() where tenant_id=t and contact_phone=ph and direction='outbound' and status='queued';
end $$;

create or replace function sms_private.api_read(u text,t text,resource text,p jsonb default '{}') returns jsonb
language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare rows jsonb; total bigint; tbl text; clause text:=''; extra text:=''; page integer; size integer; begin
 perform sms_private.require_admin(u);
 if resource='businesses' then
   return jsonb_build_object('rows',coalesce((select jsonb_agg(to_jsonb(b)) from public.sms_businesses b),'[]'));
 end if;
 if not exists(select from public.sms_businesses where tenant_id=t) then raise exception 'Unknown business'; end if;
 if resource='overview' then
   return jsonb_build_object('total',(select count(*) from public.sms_messages where tenant_id=t),
     'contactCount',(select count(*) from public.sms_contacts where tenant_id=t),
     'conversationCount',(select count(*) from public.sms_thread_contacts where tenant_id=t),
     'optedOutTotal',(select count(*) from public.sms_contacts where tenant_id=t and opted_out),
     'counts',coalesce((select jsonb_object_agg(status,n) from (select status,count(*) n from public.sms_messages where tenant_id=t group by status)s),'{}'),
     'byCategory',coalesce((select jsonb_agg(jsonb_build_object('id',category_id,'total',n)) from (select category_id,count(*) n from public.sms_messages where tenant_id=t and category_id is not null group by category_id)s),'[]'));
 elsif resource='operations' then
   return jsonb_build_object('jobs',coalesce((select jsonb_agg(s) from (select queue,status,count(*) count,min(created_at) oldest from sms_private.jobs where tenant_id=t and status not in ('completed','cancelled') group by queue,status)s),'[]'),
     'workers',coalesce((select jsonb_agg(h) from sms_private.heartbeats h),'[]'),
     'scheduler',(select to_jsonb(r) from sms_private.runtime r),
     'problems',coalesce((select jsonb_agg(s) from (select id,queue,status,error_code,created_at from sms_private.jobs where tenant_id=t and status in ('failed','submission_unknown') order by created_at desc limit 50)s),'[]'));
 end if;
 tbl:=case resource when 'contacts' then 'sms_contacts' when 'threads' then 'sms_thread_contacts' when 'messages' then 'sms_messages'
 when 'groups' then 'sms_automation_groups' when 'steps' then 'sms_automation_steps' when 'enrollments' then 'sms_automation_enrollments'
 when 'calls' then 'sms_voice_conversations' when 'ai_settings' then 'sms_ai_settings' when 'bookings' then 'sms_bookings' when 'quotes' then 'sms_quotes' end;
 if tbl is null then raise exception 'Unknown resource'; end if;
 page:=greatest(1,least(100000,coalesce((p->>'page')::integer,1))); size:=greatest(1,least(250,coalesce((p->>'pageSize')::integer,50)));
 if resource in ('contacts','threads','calls') then
   if p->>'phone' is not null then clause:=clause||format(' and phone=%L',p->>'phone'); end if;
   if p->>'q' is not null then clause:=clause||format(' and (phone ilike %L%s)','%'||(p->>'q')||'%',case when resource<>'calls' then format(' or name ilike %L','%'||(p->>'q')||'%') else '' end); end if;
 end if;
 if resource='contacts' then
   if p->>'source' is not null then clause:=clause||format(' and source=%L',p->>'source'); end if;
   if p->>'consented'='1' then clause:=clause||' and marketing_consent and not opted_out'; end if;
   if p->>'opted_out'='1' then clause:=clause||' and opted_out'; end if;
 end if;
 if resource='threads' and p->>'unread'='1' then clause:=clause||' and unread_count>0'; end if;
 if resource='messages' then
   if p->>'phone' is not null then clause:=clause||format(' and contact_phone=%L',p->>'phone'); end if;
   if p->>'status' is not null then clause:=clause||format(' and status=%L',p->>'status'); end if;
   if p->>'direction' is not null then clause:=clause||format(' and direction=%L',p->>'direction'); end if;
 end if;
 if resource in ('messages','enrollments') and p->>'category' is not null then clause:=clause||format(' and category_id=%L',p->>'category'); end if;
 if resource='steps' then clause:=clause||format(' and group_id=%L',p->>'id'); end if;
 if resource='groups' and p->>'id' is not null then clause:=clause||format(' and id=%L',p->>'id'); end if;
 if resource='contacts' then extra:=', (select coalesce(jsonb_agg(category_id),''[]'') from public.sms_automation_enrollments e where e.tenant_id=base.tenant_id and e.contact_id=base.id and e.status=''active'') as enrollments'; end if;
 if resource='enrollments' then extra:=', (select phone from public.sms_contacts c where c.tenant_id=base.tenant_id and c.id=base.contact_id) as phone, (select name from public.sms_contacts c where c.tenant_id=base.tenant_id and c.id=base.contact_id) as name'; end if;
 if resource='messages' then extra:=', (select coalesce(jsonb_agg(event),''[]'') from (select status,created_at as at,error_code from public.sms_message_events e where e.tenant_id=base.tenant_id and e.message_id=base.id order by created_at desc limit 100)event) as status_history'; end if;
 execute format('select count(*) from public.%I where tenant_id=$1%s',tbl,clause) into total using t;
 execute format('select coalesce(jsonb_agg(x),''[]'') from (select base.* %s from public.%I base where tenant_id=$1%s order by %s limit $2 offset $3)x',extra,tbl,clause,
 case when resource='steps' then 'step_index' when resource='threads' then 'last_message_at desc nulls last,phone' when resource='ai_settings' then 'group_id' when resource='calls' then 'started_at desc,conversation_id' when resource='bookings' then 'appointment_at desc,id' else 'created_at desc,id' end)
 into rows using t,size,(page-1)*size;
 return jsonb_build_object('rows',rows,'total',total,'page',page,'pageSize',size,'totalPages',greatest(1,ceil(total::numeric/size)),'configured',true);
end $$;

create or replace function public.sms_crm_list_contacts(p_tenant_id text,p_options jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column
 begin
 return sms_private.api_read(auth.jwt()->>'sub',p_tenant_id,'contacts',p_options);
end $$;
create or replace function public.sms_crm_enroll_contact(p_tenant_id text,p_contact jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column
 begin
 return sms_private.api_action(auth.jwt()->>'sub',p_tenant_id,'enroll',p_contact);
end $$;
revoke all on function public.sms_crm_list_contacts(text,jsonb),public.sms_crm_enroll_contact(text,jsonb) from public,anon;
grant execute on function public.sms_crm_list_contacts(text,jsonb),public.sms_crm_enroll_contact(text,jsonb) to authenticated;

create or replace function sms_private.job_context(jid uuid,token uuid) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare j sms_private.jobs; e public.sms_automation_enrollments; c public.sms_contacts; ph text; begin
 j:=sms_private.lease(jid,token);
 if j.queue='automation_jobs' then
   select * into e from public.sms_automation_enrollments where tenant_id=j.tenant_id and id=(j.payload->>'enrollment_id')::uuid;
   select * into c from public.sms_contacts where tenant_id=j.tenant_id and id=e.contact_id;
   return jsonb_build_object('enrollment',to_jsonb(e),'contact',to_jsonb(c),
     'business',(select to_jsonb(b) from public.sms_businesses b where tenant_id=j.tenant_id),
     'group',(select to_jsonb(g) from public.sms_automation_groups g where tenant_id=j.tenant_id and id=e.category_id),
     'steps',(select jsonb_agg(s order by step_index) from public.sms_automation_steps s where tenant_id=j.tenant_id and group_id=e.category_id));
 elsif j.queue='ai_reply_jobs' then
   ph:=j.payload->>'phone';
   return jsonb_build_object('business',(select to_jsonb(b) from public.sms_businesses b where tenant_id=j.tenant_id),
     'contact',(select to_jsonb(c) from public.sms_contacts c where tenant_id=j.tenant_id and phone=ph),
     'thread',(select to_jsonb(th) from public.sms_thread_contacts th where tenant_id=j.tenant_id and phone=ph),
     'settings',(select to_jsonb(a) from public.sms_ai_settings a where tenant_id=j.tenant_id and group_id=j.payload->>'group_id'),
     'history',(select coalesce(jsonb_agg(m order by created_at),'[]') from (select direction,body,created_at from public.sms_messages where tenant_id=j.tenant_id and contact_phone=ph order by created_at desc limit 20)m));
 elsif j.queue='provisioning_jobs' then
   return (select jsonb_build_object('account_sid',account_sid,'messaging_service_sid',messaging_service_sid,'state',provisioning_state) from sms_private.providers where tenant_id=j.tenant_id);
 end if;
 raise exception 'Unsupported context';
end $$;

create or replace function sms_private.complete_automation(jid uuid,token uuid,p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare j sms_private.jobs; e public.sms_automation_enrollments; c public.sms_contacts; g public.sms_automation_groups; result jsonb; begin
 j:=sms_private.lease(jid,token); if j.queue<>'automation_jobs' then raise exception 'Wrong queue'; end if;
 select * into e from public.sms_automation_enrollments where tenant_id=j.tenant_id and id=(j.payload->>'enrollment_id')::uuid for update;
 select * into c from public.sms_contacts where tenant_id=j.tenant_id and id=e.contact_id for update;
 select * into g from public.sms_automation_groups where tenant_id=j.tenant_id and id=e.category_id;
 if e.status<>'active' or e.generation<>(j.payload->>'generation')::bigint or e.step_index<>(j.payload->>'step_index')::int or c.opted_out or not g.active or g.version<>(p->>'group_version')::bigint then
   perform sms_private.finish(jid,token,'cancelled','STALE_ENROLLMENT'); return null;
 end if;
 if p->>'action'='complete' then
   update public.sms_automation_enrollments set status='completed',next_run_at=null where tenant_id=j.tenant_id and id=e.id;
 elsif p->>'action'='schedule' then
   update public.sms_automation_enrollments set next_run_at=(p->>'due')::timestamptz,generation=generation+1 where tenant_id=j.tenant_id and id=e.id;
 else
   result:=sms_private.outbox(j.tenant_id,'automation:'||j.dedupe_key,p-'action');
 end if;
 perform sms_private.finish(jid,token,'completed'); return result;
end $$;

create or replace function sms_private.complete_ai(jid uuid,token uuid,body text) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare j sms_private.jobs; result jsonb; begin
 j:=sms_private.lease(jid,token); if j.queue<>'ai_reply_jobs' then raise exception 'Wrong queue'; end if;
 if not exists(select from public.sms_thread_contacts th join public.sms_contacts c using(tenant_id,phone)
   where th.tenant_id=j.tenant_id and th.phone=j.payload->>'phone' and th.generation=(j.payload->>'generation')::bigint and not th.ai_paused and not c.opted_out)
   or not exists(select from public.sms_ai_settings where tenant_id=j.tenant_id and group_id=j.payload->>'group_id' and enabled) then
   perform sms_private.finish(jid,token,'cancelled','STALE_REPLY'); return null;
 end if;
 result:=sms_private.outbox(j.tenant_id,'ai:'||j.id,jsonb_build_object('phone',j.payload->>'phone','body',body,'purpose','transactional','category_id',j.payload->>'group_id','conversation_generation',j.payload->'generation'));
 perform sms_private.finish(jid,token,'completed'); return result;
end $$;

create or replace function sms_private.ai_tool(jid uuid,token uuid,name text,args jsonb,call_id text) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare j sms_private.jobs; cid uuid; result jsonb; begin
 j:=sms_private.lease(jid,token); if j.queue<>'ai_reply_jobs' then raise exception 'Wrong queue'; end if;
 select id into strict cid from public.sms_contacts where tenant_id=j.tenant_id and phone=j.payload->>'phone' and not opted_out;
 if not exists(select from public.sms_thread_contacts where tenant_id=j.tenant_id and phone=j.payload->>'phone' and not ai_paused and generation=(j.payload->>'generation')::bigint) then raise exception 'Stale reply'; end if;
 if name='list_bookings' then
   select coalesce(jsonb_agg(b),'[]') into result from public.sms_bookings b where tenant_id=j.tenant_id and contact_id=cid;
 elsif name='request_booking' then
   if (args->>'appointment_at')::timestamptz<=now() then raise exception 'Future appointment required'; end if;
   insert into public.sms_bookings(tenant_id,id,contact_id,appointment_at,status,metadata)
   values(j.tenant_id,'ai:'||j.id||':'||md5(args::text),cid,(args->>'appointment_at')::timestamptz,'requested',jsonb_build_object('notes',args->>'notes'))
   on conflict(tenant_id,id) do nothing;
   result:=jsonb_build_object('status','requested','message','A booking request was saved; it is not confirmed.');
 else raise exception 'Tool not permitted'; end if;
 return result;
end $$;

create or replace function sms_private.provision_checkpoint(jid uuid,token uuid,p jsonb) returns void language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare j sms_private.jobs; sec uuid; begin
 j:=sms_private.lease(jid,token); if j.queue<>'provisioning_jobs' then raise exception 'Wrong queue'; end if;
 if p ? 'auth_token' then select vault.create_secret(p->>'auth_token') into sec; end if;
 update sms_private.providers set account_sid=coalesce(p->>'account_sid',account_sid),auth_secret_id=coalesce(sec,auth_secret_id),
   messaging_service_sid=coalesce(p->>'messaging_service_sid',messaging_service_sid),provisioning_state=p->>'state' where tenant_id=j.tenant_id;
end $$;

create or replace function sms_private.webhook_credentials(account text) returns jsonb language sql security definer set search_path='' as $$
 select jsonb_build_object('tenant_id',p.tenant_id,'auth_token',s.decrypted_secret,'from_number',p.from_number)
 from sms_private.providers p join vault.decrypted_secrets s on s.id=p.auth_secret_id where p.account_sid=account
$$;
create or replace function sms_private.integration_credentials(t text) returns text language sql security definer set search_path='' as $$
 select s.decrypted_secret from sms_private.providers p join vault.decrypted_secrets s on s.id=p.integration_secret_id where p.tenant_id=t
$$;

create or replace function sms_private.record_webhook(t text,event text,p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare c public.sms_contacts; mid uuid; th public.sms_thread_contacts; gid text; a sms_private.attempts; j sms_private.jobs; s text; key text; begin
 key:=event||':'||coalesce(p->>'MessageSid',p->>'CallSid')||':'||coalesce(p->>'MessageStatus',p->>'CallStatus','inbound');
 insert into sms_private.webhook_events(tenant_id,event_key) values(t,key) on conflict do nothing;
 if not found then return jsonb_build_object('duplicate',true); end if;
 if event='inbound' then
   insert into public.sms_contacts(tenant_id,phone) values(t,p->>'From') on conflict do nothing;
   select * into strict c from public.sms_contacts where tenant_id=t and phone=p->>'From' for update;
   insert into public.sms_messages(tenant_id,sid,contact_phone,direction,body,status) values(t,p->>'MessageSid',c.phone,'inbound',coalesce(nullif(p->>'Body',''),'[Media message]'),'received') returning id into mid;
   insert into public.sms_thread_contacts(tenant_id,phone,name,generation,unread_count,last_body,last_direction,last_message_at,last_inbound_at)
   values(t,c.phone,c.name,1,1,p->>'Body','inbound',now(),now()) on conflict(tenant_id,phone) do update set generation=sms_thread_contacts.generation+1,
     unread_count=sms_thread_contacts.unread_count+1,last_body=excluded.last_body,last_direction='inbound',last_message_at=now(),last_inbound_at=now() returning * into th;
   s:=upper(trim(coalesce(p->>'OptOutType',p->>'Body','')));
   if s in ('STOP','STOPALL','UNSUBSCRIBE','CANCEL','END','QUIT','REVOKE','OPTOUT','START','UNSTOP') then
     update public.sms_contacts set opted_out=s not in ('START','UNSTOP'),marketing_consent=s in ('START','UNSTOP'),generation=generation+1,updated_at=now() where tenant_id=t and id=c.id;
     insert into public.sms_consent_events(tenant_id,contact_id,consent,source,evidence) values(t,c.id,s in ('START','UNSTOP'),'twilio',p->>'MessageSid');
     if s not in ('START','UNSTOP') then perform sms_private.cancel_contact(t,c.id); end if;
     return jsonb_build_object('consent_event',true);
   end if;
   update public.sms_automation_enrollments set next_run_at=greatest(next_run_at,now()+interval '24 hours'),generation=generation+1
   where tenant_id=t and contact_id=c.id and status='active' and category_id in(select id from public.sms_automation_groups where tenant_id=t and kind<>'reminder');
   select a.group_id into gid from public.sms_ai_settings a join public.sms_automation_enrollments e on e.tenant_id=a.tenant_id and e.category_id=a.group_id
   where a.tenant_id=t and e.contact_id=c.id and e.status='active' and a.enabled order by e.created_at desc limit 1;
   if gid is not null and not th.ai_paused and not c.opted_out then
     perform sms_private.enqueue(t,'ai_reply_jobs',p->>'MessageSid',jsonb_build_object('phone',c.phone,'generation',th.generation,'group_id',gid));
   end if;
 elsif event='status' then
   if p->>'attempt_id' is not null then
     select * into strict a from sms_private.attempts where id=(p->>'attempt_id')::uuid;
     select * into strict j from sms_private.jobs where id=a.job_id and tenant_id=t;
     perform sms_private.accept_attempt(a.id,p->>'MessageSid'); mid:=(j.payload->>'message_id')::uuid;
   else select id into strict mid from public.sms_messages where tenant_id=t and sid=p->>'MessageSid'; end if;
   s:=p->>'MessageStatus';
   insert into public.sms_message_events(tenant_id,message_id,status,error_code) values(t,mid,s,p->>'ErrorCode');
   update public.sms_messages set status=s,error_code=p->>'ErrorCode',updated_at=now() where tenant_id=t and id=mid
     and sms_private.status_rank(s)>sms_private.status_rank(status);
 elsif event='call' then
   if p->>'Direction' is not null and p->>'Direction'<>'inbound' then raise exception 'Only inbound calls supported'; end if;
   insert into public.sms_voice_conversations(tenant_id,conversation_id,phone,status,duration_secs)
   values(t,p->>'CallSid',p->>'From',p->>'CallStatus',(p->>'CallDuration')::integer)
   on conflict(tenant_id,conversation_id) do update set status=excluded.status,duration_secs=coalesce(excluded.duration_secs,sms_voice_conversations.duration_secs);
 else raise exception 'Unknown event'; end if;
 return jsonb_build_object('ok',true);
end $$;
create or replace function sms_private.status_rank(s text) returns integer language sql immutable set search_path='' as $$
 select case s when 'queued' then 0 when 'submitting' then 1 when 'accepted' then 2 when 'sending' then 3 when 'sent' then 4 when 'failed' then 5 when 'undelivered' then 5 when 'delivered' then 6 when 'read' then 7 else -1 end
$$;

create or replace function sms_private.ingest_event(t text,p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_column

declare c public.sms_contacts; gid text; begin
 insert into sms_private.webhook_events(tenant_id,event_key) values(t,'integration:'||(p->>'eventId')) on conflict do nothing;
 if not found then return jsonb_build_object('duplicate',true); end if;
 insert into public.sms_contacts(tenant_id,phone,name,source) values(t,p->>'phone',coalesce(p->>'name',''),'booking') on conflict do nothing;
 select * into strict c from public.sms_contacts where tenant_id=t and phone=p->>'phone' for update;
 if p->>'type' in ('booking.created','booking.rescheduled','booking.cancelled') then
   insert into public.sms_bookings(tenant_id,id,contact_id,appointment_at,status,metadata)
   values(t,p->>'id',c.id,(p->>'appointment_at')::timestamptz,case when p->>'type'='booking.cancelled' then 'cancelled' else 'confirmed' end,coalesce(p->'metadata','{}'))
   on conflict(tenant_id,id) do update set appointment_at=excluded.appointment_at,status=excluded.status,metadata=excluded.metadata,updated_at=now();
   update public.sms_automation_enrollments set status='cancelled',generation=generation+1 where tenant_id=t and contact_id=c.id and status in ('active','paused')
   and category_id in(select id from public.sms_automation_groups where tenant_id=t and kind in ('quote','reminder'));
   if p->>'type'<>'booking.cancelled' and not c.opted_out and (p->>'appointment_at')::timestamptz>now() then
     select id into gid from public.sms_automation_groups where tenant_id=t and kind='reminder' and active order by created_at limit 1;
     if gid is not null then insert into public.sms_automation_enrollments(tenant_id,contact_id,category_id,appointment_at,next_run_at,metadata)
       values(t,c.id,gid,(p->>'appointment_at')::timestamptz,now(),jsonb_build_object('booking_id',p->>'id')||coalesce(p->'metadata','{}')); end if;
   end if;
 elsif p->>'type'='quote.created' then
   insert into public.sms_quotes(tenant_id,id,contact_id,details) values(t,p->>'id',c.id,coalesce(p->'metadata','{}')) on conflict do nothing;
   select id into gid from public.sms_automation_groups where tenant_id=t and kind='quote' and active order by created_at limit 1;
   if gid is not null and c.marketing_consent and not c.opted_out then
     insert into public.sms_automation_enrollments(tenant_id,contact_id,category_id,next_run_at,metadata) values(t,c.id,gid,now(),coalesce(p->'metadata','{}')) on conflict do nothing;
   end if;
 else raise exception 'Unsupported event'; end if;
 return jsonb_build_object('ok',true);
end $$;

-- Explicit function grants; no application login gets table, queue or Vault access.
revoke all on schema pgmq from public,anon,authenticated,sms_api,sms_webhook,sms_sender,sms_automation,sms_ai;
revoke all on all functions in schema sms_private from public,anon,authenticated,sms_api,sms_webhook,sms_sender,sms_automation,sms_ai;
grant execute on function sms_private.can_access(text,text) to authenticated;
grant execute on function sms_private.api_action(text,text,text,jsonb),sms_private.api_read(text,text,text,jsonb) to sms_api;
grant execute on function sms_private.webhook_credentials(text),sms_private.record_webhook(text,text,jsonb),sms_private.integration_credentials(text),sms_private.ingest_event(text,jsonb) to sms_webhook;
grant execute on function sms_private.claim(text,text),sms_private.extend_lease(uuid,uuid),sms_private.finish(uuid,uuid,text,text,integer) to sms_sender,sms_automation,sms_ai;
grant execute on function sms_private.begin_submission(uuid,uuid),sms_private.accept_submission(uuid,uuid,uuid,text) to sms_sender;
grant execute on function sms_private.job_context(uuid,uuid) to sms_automation,sms_ai;
grant execute on function sms_private.complete_automation(uuid,uuid,jsonb),sms_private.provision_checkpoint(uuid,uuid,jsonb) to sms_automation;
grant execute on function sms_private.complete_ai(uuid,uuid,text),sms_private.ai_tool(uuid,uuid,text,jsonb,text) to sms_ai;
select cron.schedule('sms-scheduler','30 seconds','select sms_private.tick()');


create index if not exists sms_audit_actor_time on sms_private.audit(actor,created_at desc);
create index if not exists sms_events_message on public.sms_message_events(tenant_id,message_id,created_at desc);
create index if not exists sms_enrollments_contact on public.sms_automation_enrollments(tenant_id,contact_id);
create index if not exists sms_jobs_lease on sms_private.jobs(leased_until) where status in ('processing','submitting');
create index if not exists sms_jobs_tenant_status on sms_private.jobs(tenant_id,status,created_at);

create or replace function sms_private.attempt_outcome() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if new.queue='sms_send_jobs' and old.status='submitting' and new.status in ('retry','failed','submission_unknown') then
   update sms_private.attempts set state=case when new.status='submission_unknown' then 'unknown' else 'rejected' end
   where job_id=new.id and lease_token=old.lease_token and sid is null;
 end if;
 return new;
end $$;
drop trigger if exists sms_attempt_outcome on sms_private.jobs;
create trigger sms_attempt_outcome after update of status on sms_private.jobs for each row execute function sms_private.attempt_outcome();
revoke all on function sms_private.attempt_outcome() from public,anon,authenticated;

create or replace function sms_private.delivery_failure() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if new.status in ('failed','undelivered') then
   update public.sms_automation_enrollments e set status='paused',generation=e.generation+1
   from sms_private.jobs j where j.tenant_id=new.tenant_id and j.payload->>'message_id'=new.message_id::text
   and e.tenant_id=j.tenant_id and e.id=(j.payload->'request'->>'enrollment_id')::uuid
   and e.generation=(j.payload->'request'->>'enrollment_generation')::bigint and e.status='active';
 end if;
 return new;
end $$;
drop trigger if exists sms_delivery_failure on public.sms_message_events;
create trigger sms_delivery_failure after insert on public.sms_message_events for each row execute function sms_private.delivery_failure();
revoke all on function sms_private.delivery_failure() from public,anon,authenticated;

